routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
], function () {

    /*
     * Frontend Routes
     */
    Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
        include_route_files(__DIR__.'/frontend/');
    });

    /*
     * Backend Routes
     */
    Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.'], function () {
        include_route_files(__DIR__ . '/backend/');
    });

    Route::get('search/query', ['as' => 'search.query', 'uses' => 'Api\SearchController@query']);
    Route::get('search/add', ['as' => 'search.add', 'uses' => 'Api\SearchController@add']);
    Route::get('search/delete', ['as' => 'search.delete', 'uses' => 'Api\SearchController@delete']);

});

Route::group([
    'prefix' => 'common',
    'as'  => 'common.',
    'namespace' => 'Api',
    'middleware' => 'admin'
], function () {
    Route::get('get_menu/{type}/{id?}', ['as' => 'menu', 'uses' => 'CommonApiController@get_menu']);
    Route::get('get_menu_parent/{type}/{id?}', ['as' => 'menu.parent', 'uses' => 'CommonApiController@get_menu_parent']);
    Route::get('get_group', ['as' => 'group', 'uses' => 'CommonApiController@get_group']);
    Route::get('get_group_admin', ['as' => 'group.admin', 'uses' => 'CommonApiController@get_group_admin']);
    Route::get('get_page', ['as' => 'page', 'uses' => 'CommonApiController@get_page']);
    Route::get('get_module', ['as' => 'module', 'uses' => 'CommonApiController@get_module']);
    Route::get('get_post', ['as' => 'post', 'uses' => 'CommonApiController@get_post']);
    Route::get('get_users', ['as' => 'users', 'uses' => 'CommonApiController@get_users']);
});

//Uploader Route
Route::group([
    'prefix' => 'service/uploads',
    'as'  => 'service.uploads.',
    'namespace' => 'Api',
    'middleware' => 'admin'
], function () {
    Route::post('multiple', ['as'=>'multiple','uses'=>'UploadHandlerController@fileMultipleUpload']);
    Route::post('single', ['as'=>'single','uses'=>'UploadHandlerController@fileSingleUpload']);
    Route::post('document', ['as'=>'document','uses'=>'UploadHandlerController@docSingleUpload']);
    Route::get('remove/{id}', ['as'=>'remove','uses'=>'UploadHandlerController@fileRemove']);
    Route::get('batch/{id}', ['as'=>'batch','uses'=>'UploadHandlerController@fileRemoveBatch']);
    Route::get('preview/{id?}/{w?}/{h?}', ['as'=>'preview','uses'=>'UploadHandlerController@filePreview']);
    Route::post('all', ['as'=>'all','uses'=>'UploadHandlerController@filePreviewMultiple']);
    Route::post('post-remove', ['as' => 'post.remove', 'uses' => 'UploadHandlerController@postRemove']);
    Route::post('remove-asset', ['as' => 'remove.asset', 'uses' => 'UploadHandlerController@removeAsset']);
    Route::post('editor', ['as' => 'editor', 'uses' => 'UploadHandlerController@editorUpload']);
    Route::get('manager', ['as' => 'manager', 'uses' => 'UploadHandlerController@editorManager']);
    Route::delete('manager-remove', ['as' => 'manager.remove', 'uses' => 'UploadHandlerController@editorManagerDelete']);
});

app/Models/Modules/Extension/BannerModel.php
<?php
/**
 * Description: BannerModel.php generated by PhpStorm.
 * @project     web-sekolah
 * @package     App\Models\Modules\Extension
 * @author      alex
 * @created     2020-06-06, modified: 2020-06-06 22:32
 * @copyright   Copyright (c) 2020
 */

namespace App\Models\Modules\Extension;


use App\Models\Traits\Method\StatusMethod;
use Illuminate\Database\Eloquent\Model;

class BannerModel extends Model
{
    use StatusMethod;

    protected $table = 'ms_banner';
    protected $primaryKey = 'id';
    protected $fillable = ['title', 'image', 'position', 'link', 'show', 'status', 'created_by', 'updated_by'];
    protected $guarded = ['created_at', 'updated_at'];
    protected $attributes = [
        'status' => true,
        'show' => true
    ];
    protected $casts = [
        'status' => 'boolean',
        'show' => 'boolean'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function asset()
    {
        return $this->belongsTo('App\Models\Services\UploadHandlerModel', 'image', 'assetId');
    }
}

app/Models/Modules/Extension/SliderModel.php
<?php
/**
 * Description: SliderModel.php generated by PhpStorm.
 * @project     web-sekolah
 * @package     App\Models\Modules\Extension
 * @author      alex
 * @created     2020-05-14, modified: 2020-05-14 02:02
 * @copyright   Copyright (c) 2020
 */

namespace App\Models\Modules\Extension;


use App\Models\Traits\Method\StatusMethod;
use Illuminate\Database\Eloquent\Model;

class SliderModel extends Model
{
    use StatusMethod;

    protected $table = 'ms_slider';
    protected $primaryKey = 'id';
    protected $fillable = ['title', 'image', 'status', 'sort_order', 'created_by', 'updated_by'];
    protected $guarded = ['created_at', 'updated_at'];
    protected $attributes = [
        'status' => true
    ];
    protected $casts = [
        'status' => 'boolean'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function asset()
    {
        return $this->belongsTo('App\Models\Services\UploadHandlerModel', 'image', 'assetId');
    }
}

app/Http/Controllers/Backend/Modules/Extension/BannerController.php
<?php
/**
 * Description: BannerController.php generated by PhpStorm.
 * @project     web-sekolah
 * @package     App\Http\Controllers\Backend\Modules\Extension
 * @author      alex
 * @created     2020-06-06, modified: 2020-06-06 22:30
 * @copyright   Copyright (c) 2020
 */

namespace App\Http\Controllers\Backend\Modules\Extension;


use App\Exceptions\GeneralException;
use App\Http\Controllers\Api\UploadHandlerController;
use App\Http\Controllers\Controller;
use App\Repositories\Modules\Extension\BannerRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

/**
 * @property UploadHandlerController handlerController
 * @property BannerRepository        repository
 */
class BannerController extends Controller
{
    private $route = "admin.extension.banner";
    private $template = "backend.modules.extension.banner";

    /**
     * BannerController constructor.
     *
     * @param BannerRepository        $repository
     * @param UploadHandlerController $handlerController
     */
    public function __construct(BannerRepository $repository,
                                UploadHandlerController $handlerController)
    {
        $this->repository = $repository;
        $this->handlerController = $handlerController;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        permission('is_read', $this->getRoute(), false, 'module');
        $data['route'] = $this->route;
        $data['title'] = __('strings.common.list') . ' ' . __('module.banner.module');
        return view($this->template . '.index', $data);
    }

    /**
     * @return mixed
     * @throws \Exception
     */
    public function grid()
    {
        $dataArray = $this->repository->get();
        $_data = [];
        foreach ($dataArray as $row) {
            $_data[] = [
                'secureId' => encode_id($row->id),
                'ids' => $row->id,
                'title' => $row->title,
                'position' => $row->position,
                'image' => $row->asset->getFullURLAttribute(),
                'status' => $row->status
            ];
        }
        return response()->json($_data);
    }

    /**
     * @param null $id
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function update($id = null)
    {
        if ($id) {
            permission('is_update', $this->getRoute(), false, 'module');
            $keyId = decode_id($id);
            $data['item'] = $this->repository->getById($keyId);
            $data['title'] = __('strings.common.edit') . ' ' . __('module.banner.module');
        } else {
            permission('is_create', $this->getRoute(), false, 'module');
            $data['item'] = null;
            $data['title'] = __('strings.common.add') . ' ' . __('module.banner.module');
        }
        $data['secure_id'] = $id;
        $data['route'] = $this->route;
        return view($this->template . '.form', $data);
    }

    /**
     * @param Request $request
     *
     * @return \Illuminate\Http\RedirectResponse
     * @throws GeneralException
     */
    public function store(Request $request)
    {
        if ($request->all()) {
            $keyId = decode_id($request->input('secure_id'));
            Validator::make($request->all(), [
                'title' => 'required',
                'image' => 'required',
                'position' => 'required',
            ], [
                'title.required' => __('validation.required', ['attribute' => __('forms.banner.name')]),
                'image.required' => __('validation.required', ['attribute' => __('forms.banner.image')]),
                'position.required' => __('validation.required', ['attribute' => __('forms.banner.position')]),
            ])->validate();

            $data = $request->all();
            $data['status'] = $request->has('status');
            if (!$request->input('secure_id')) {
                permission('is_create', $this->getRoute(), false, 'module');
                $data['created_by'] = Auth::id();
                $result = $this->repository->create($data);
                if ($result) {
                    logActivity($request, __('strings.backend.logs.add', ['val' => strtolower(__('module.banner.module')) . ' ' . $result->title]));
                    return redirect()->route($this->getRoute('index'))->with('message', __('strings.common.messages.save.success'))
                        ->with('type', 'success');
                } else {
                    throw new GeneralException(__('strings.common.messages.save.failed'));
                }
            } else {
                permission('is_update', $this->getRoute(), false, 'module');
                $data['updated_by'] = Auth::id();
                $result = $this->repository->updateById($keyId, $data);
                if ($result) {
                    logActivity($request, __('strings.backend.logs.edit', ['val' => strtolower(__('module.banner.module')) . ' ' . $result->title]));
                    return redirect()->route($this->getRoute('index'))->with('message', __('strings.common.messages.update.success'))
                        ->with('type', 'success');
                } else {
                    throw new GeneralException(__('strings.common.messages.update.failed'));
                }
            }
        } else {
            throw new GeneralException(__('strings.common.messages.empty'));
        }
    }

    /**
     * @param Request $request
     *
     * @return \Illuminate\Http\RedirectResponse
     * @throws GeneralException
     * @throws \Exception
     */
    public function destroy(Request $request)
    {
        permission('is_delete', $this->getRoute(), false, 'module');
        if (!$request->input('secure_id')) {
            throw new GeneralException(__('strings.common.messages.empty'));
        }

        $id = decode_id($request->input('secure_id'));
        $data = $this->repository->getById($id);
        if ($data) {
            if ($data->delete()) {
                if ($data->image) $this->handlerController->fileRemove($data->image);
                logActivity($request, __('strings.backend.logs.delete', ['val' => strtolower(__('module.banner.module')) . ' ' . $data->title]));
                return redirect()->route($this->getRoute('index'))->with('message', __('strings.common.messages.delete.success'))
                    ->with('type', 'success');
            } else {
                throw new GeneralException(__('strings.common.messages.delete.failed'));
            }
        } else {
            throw new GeneralException(__('strings.common.messages.not_found'));
        }
    }

    /**
     * @param Request $request
     *
     * @return \Illuminate\Http\RedirectResponse
     * @throws GeneralException
     * @throws \Exception
     */
    public function batch(Request $request)
    {
        permission('is_delete', $this->getRoute(), false, 'module');
        if (!$request->input('ids')) {
            throw new GeneralException(__('strings.common.messages.empty'));
        }

        $all = $this->repository->whereIn('id', $request->input('ids'))->get();
        $_images = [];
        foreach ($all as $row) {
            $_images[] = $row->image;
        }
        $this->handlerController->fileRemoveBatch($_images);
        $result = $this->repository->deleteMultipleById($request->input('ids'));
        if ($result) {
            logActivity($request, __('strings.backend.logs.batch', ['val' => implode(',', $request->input('ids'))]));
            return redirect()->route($this->getRoute('index'))->with('message', __('strings.common.messages.delete.success'))
                ->with('type', 'success');
        } else {
            throw new GeneralException(__('strings.common.messages.delete.failed'));
        }
    }

    /**
     * @param string $prefix
     *
     * @return string
     */
    public function getRoute($prefix = '*'): string
    {
        return $this->route . '.' . $prefix;
    }
}

resources/views/backend/modules/extension/banner/form.blade.php
@extends('backend._container.layout')
@section('title', $title)
@section('breadcrumbs')
    {{ Breadcrumbs::render('banner') }}
@stop
@section('content')
    <div class="container-fluid">
        <div id="ui-view">
            <div class="fade-in">
                <div class="card card-accent-secondary">
                    <div class="card-header d-flex align-items-center">
                        <h5 class="card-title mb-0"><i class="fas fa-edit"></i> {{$title}}</h5>
                        <button class="btn btn-secondary mfs-auto mfe-1 d-print-none"
                                onclick="clickButton('{{route($route.'.index')}}')"><span
                                    class="fas fa-arrow-left"></span> @lang('buttons.general.back')</button>
                    </div>
                    {!! Form::open(['route' => $route.'.store','id' => 'appForm', 'novalidate' => 'novalidate']) !!}
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-8 col-sm-12 col-xs-12">
                                @include('backend.errors.list')
                                <div class="form-group {{ $errors->has('title') ? ' has-error' : '' }}">
                                    {!! Form::label('title', __('forms.banner.name'),['class' => 'required-label']) !!}
                                    {!! Form::text('title', @$item->title ? $item->title : old('title'),['class' => 'form-control', 'required' => true]); !!}
                                </div>
                                <div class="form-group">
                                    {!! Form::label('link', __('forms.banner.link')) !!}
                                    {!! Form::text('link', @$item->link ? $item->link : old('link'),['class' => 'form-control']); !!}
                                </div>
                                <div class="form-group {{ $errors->has('image') ? ' has-error' : '' }}">
                                    {!! Form::label('assetId', __('forms.banner.image'),['class' => 'required-label']) !!}
                                    <div id="uploadBanner" class="dropzone"></div>
                                    {!! Form::hidden('image', @$item->image ? $item->image : old('image'), ['id' => 'assetId', 'required' => true]) !!}
                                    <ul class="list-unstyled text-primary mb-0">
                                        <li>
                                            <small>{!! __('strings.common.upload_limit',['num' => 1]) !!}</small>
                                        </li>
                                        <li>
                                            <small>{!! __('strings.common.upload_size',['num' => imageSize()]) !!}MB;
                                            </small>
                                        </li>
                                        <li>
                                            <small>{!! __('strings.common.upload_ext',['ext' => imageExt()]) !!}</small>
                                        </li>
                                    </ul>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-sm-12 col-xs-12">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="card-header px-0 pt-0">
                                            <strong><i class="fas fa-cogs"></i> @lang('strings.common.option')</strong>
                                        </div>
                                        <div class="card-body px-0 pb-0">
                                            <div class="form-row mb-4">
                                                {!! Form::label('position', __('forms.banner.position'), ['class' => 'col-md-4 control-label']); !!}
                                                <div class="col-md-8">
                                                    {!! Form::select('position', ['home' => 'Halaman Depan','sidebar' => 'Sidebar'], @$item->position, ['class' => 'form-control select2-nosearch']); !!}
                                                </div>
                                            </div>
                                            <div class="form-row">
                                                {!! Form::label('status', __('strings.common.status.label'), ['class' => 'col-md-4 control-label']); !!}
                                                <div class="col-md-3">
                                                    <label class="c-switch c-switch-label c-switch-pill c-switch-success">
                                                        <input type="checkbox" name="status" class="c-switch-input"
                                                               @if(@$item->status == true) checked @endif>
                                                        <span class="c-switch-slider" data-checked="&#x2713"
                                                              data-unchecked="&#x2715"></span>
                                                    </label>
                                                </div>
                                                <div class="col-md-5">
                                                    <small class="text-muted">@lang('strings.common.notes.publish')</small>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        {!! Form::hidden('secure_id', @$secure_id) !!}
                        <button onclick="clickButton('{{route($route.'.index')}}')" class="ladda-button" type="button"
                                data-size="s" data-color="red" data-style="slide-right"><i class="fas fa-times"></i>
                            <span class="ladda-label">@lang('buttons.general.cancel')</span></button>
                        <button type="submit" class="ladda-button" data-size="s" data-color="green"
                                data-style="slide-right"><i
                                    class="fas fa-save"></i> <span
                                    class="ladda-label">@lang('buttons.general.save')</span></button>
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
@stop
@push('after-styles')
    {{ Html::style(app_vendor('dropzone/dropzone.min.css')) }}
@endpush
@push('after-scripts')
    {{ Html::script(app_vendor('dropzone/dropzone.min.js'), ['type' => 'text/javascript']) }}
    <script type="text/javascript">
        document.querySelector("html").classList.add('js');
        Dropzone.autoDiscover = false;
        $('document').ready(function () {
            let $upload = $('#uploadBanner');
            let csrf = $('input[name="_token"]');
            let $assetId = $('#assetId');
            let optParams = {
                _token: csrf.val(),
                dataId: '{{@$secure_id}}',
                category: 'BANNER',
                baseFolder: 'images',
                title: $('input[name="title"]').val()
            };

            let $prevUrl = null;
            if (!$.isEmpty($assetId.val())) {
                $prevUrl = '{{url('service/uploads/preview')}}/' + $assetId.val() + '/750/500';
            }
            let uploadOptions = {
                url: '{{route('service.uploads.single')}}',
                previewUrl: $prevUrl,
                removeUrl: '{{route('service.uploads.post.remove')}}',
                acceptedFiles: '{!! imageExt() !!}',
                maxFiles: 1,
                maxFilesize: '{!! imageSize() !!}',
                thumbnailWidth: 750,
                thumbnailHeight: 500
            };

            $upload.singleUpload($.apply({
                params: optParams
            }, uploadOptions));

        });
    </script>
@endpush

resources/views/backend/modules/extension/banner/index.blade.php
@extends('backend._container.layout')
@section('title', $title)
@section('breadcrumbs')
    {{ Breadcrumbs::render('banner') }}
@stop
@section('content')
    <div class="container-fluid">
        <div id="ui-view">
            <div>
                <div class="fade-in">
                    <div class="card card-accent-secondary">
                        <div class="card-header d-flex align-items-center">
                            <h5 class="card-title mb-0"><i class="fas fa-list-alt"></i> {{$title}}</h5>
                            <div class="btn-group mfs-auto" role="group">
                                @if(access('is_create', $route.'.*'))
                                    <button onclick="clickButton('{{ route($route.'.update') }}')" type="button"
                                            class="btn btn-outline-primary">
                                        <i class="fas fa-plus"></i> @lang('buttons.general.create')
                                    </button>
                                @endif
                                @if(access('is_delete', $route.'.*'))
                                    <button id="btnRemoveAll" type="button" class="btn btn-outline-danger">
                                        <i class="fas fa-trash"></i> @lang('buttons.general.delete')
                                    </button>
                                @endif
                            </div>
                        </div>
                        <div class="card-body card-body-table">
                            {{ Form::open(['route' => $route.'.batch','id' => 'batchDelete']) }}
                            <table class="table table-responsive-sm table-striped table-hover table-bordered table-header-center text-nowrap"
                                   data-search="true"
                                   data-show-refresh="true"
                                   data-toggle="table"
                                   data-url="{{route($route.'.grid')}}"
                                   data-sort-name="ids"
                                   data-sort-order="desc"
                                   data-id-field="id"
                                   id="grid-data">
                                <thead>
                                <tr>
                                    <th data-width="25" data-align="center" data-formatter="checkAll">
                                        <input type="checkbox" class="checkall" data-toggle="tooltip"
                                               data-placement="top"
                                               title="@lang('strings.common.select_all')">
                                    </th>
                                    <th data-field="title" data-class="nowrap">@lang('forms.banner.name')</th>
                                    <th data-field="position" data-class="nowrap">@lang('forms.banner.position')</th>
                                    <th data-field="status" data-formatter="statusFormatter"
                                        data-align="center" data-width="100">@lang('strings.common.status.label')</th>
                                    <th data-field="commands" data-class="nowrap" data-width="100"
                                        data-formatter="commandAction"
                                        data-events="commandEvents">@lang('strings.common.status.action')
                                    </th>
                                </tr>
                                </thead>
                            </table>
                            {{ Form::close() }}
                            <div class="hidden">
                                {{ Form::open(['route' => $route.'.destroy','id' => 'formDelete']) }}
                                {{ Form::hidden('secure_id', null, ['id' => 'row-id']) }}
                                {{ Form::close() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@push('after-scripts')
    <script type="text/javascript">
        function commandAction(value, row, index) {
            let button = '<div class="btn-group btn-group-sm" role="group">';
            @if(access('is_update', $route.'.*'))
                button += '<button type="button" class="btn btn-info btn-sm command-edit"><i class="fas fa-edit"></i></button>';
            @endif
                    @if(access('is_delete', $route.'.*'))
                button += '<button type="button" class="btn btn-danger btn-sm command-delete"><i class="fas fa-trash"></i></button>';
            @endif
                button += '</div>';
            return button;
        }

        function statusFormatter(value, row) {
            let icon = '<i class="fas fa-check text-success" data-toggle="tooltip" data-placement="top" data-original-title="@lang('strings.common.status.active')"></i>';
            if (row['status'] === false) {
                icon = '<i class="fas fa-times text-danger" data-toggle="tooltip" data-placement="top" data-original-title="@lang('strings.common.status.inactive')"></i>';
            }
            return icon;
        }

        $(document).ready(function () {
            window.commandEvents = {
                'click .command-edit': function (e, value, row) {
                    e.preventDefault();
                    $(location).attr('href', '{{url('admin/extension/banner/update')}}/' + row['secureId']);
                },
                'click .command-delete': function (e, value, row) {
                    e.preventDefault();
                    $('#row-id').val(row['secureId']);
                    Swal.fire({
                        title: '<i class="fas fa-exclamation-triangle text-danger"></i>&nbsp;{!! __('strings.common.messages.delete.confirmation') !!}',
                        html: '{!! __('strings.common.messages.delete.confirm_data') !!}' + '<strong>' + row['title'] + '</strong>?',
                        showCancelButton: true,
                        confirmButtonText: '{!! __('buttons.general.yes') !!}',
                        cancelButtonText: '{!! __('buttons.general.no') !!}',
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        allowOutsideClick: false,
                        allowEnterKey: false
                    }).then((result) => {
                        result.value && $('#formDelete').submit();
                    });
                }
            };
        });
    </script>
@endpush