routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
], function () {

    /*
     * Frontend Routes
     */
    Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
        include_route_files(__DIR__.'/frontend/');
    });

    /*
     * Backend Routes
     */
    Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.'], function () {
        include_route_files(__DIR__ . '/backend/');
    });

    Route::get('search/query', ['as' => 'search.query', 'uses' => 'Api\SearchController@query']);
    Route::get('search/add', ['as' => 'search.add', 'uses' => 'Api\SearchController@add']);
    Route::get('search/delete', ['as' => 'search.delete', 'uses' => 'Api\SearchController@delete']);

});

Route::group([
    'prefix' => 'common',
    'as'  => 'common.',
    'namespace' => 'Api',
    'middleware' => 'admin'
], function () {
    Route::get('get_menu/{type}/{id?}', ['as' => 'menu', 'uses' => 'CommonApiController@get_menu']);
    Route::get('get_menu_parent/{type}/{id?}', ['as' => 'menu.parent', 'uses' => 'CommonApiController@get_menu_parent']);
    Route::get('get_group', ['as' => 'group', 'uses' => 'CommonApiController@get_group']);
    Route::get('get_group_admin', ['as' => 'group.admin', 'uses' => 'CommonApiController@get_group_admin']);
    Route::get('get_page', ['as' => 'page', 'uses' => 'CommonApiController@get_page']);
    Route::get('get_module', ['as' => 'module', 'uses' => 'CommonApiController@get_module']);
    Route::get('get_post', ['as' => 'post', 'uses' => 'CommonApiController@get_post']);
    Route::get('get_users', ['as' => 'users', 'uses' => 'CommonApiController@get_users']);
});

//Uploader Route
Route::group([
    'prefix' => 'service/uploads',
    'as'  => 'service.uploads.',
    'namespace' => 'Api',
    'middleware' => 'admin'
], function () {
    Route::post('multiple', ['as'=>'multiple','uses'=>'UploadHandlerController@fileMultipleUpload']);
    Route::post('single', ['as'=>'single','uses'=>'UploadHandlerController@fileSingleUpload']);
    Route::post('document', ['as'=>'document','uses'=>'UploadHandlerController@docSingleUpload']);
    Route::get('remove/{id}', ['as'=>'remove','uses'=>'UploadHandlerController@fileRemove']);
    Route::get('batch/{id}', ['as'=>'batch','uses'=>'UploadHandlerController@fileRemoveBatch']);
    Route::get('preview/{id?}/{w?}/{h?}', ['as'=>'preview','uses'=>'UploadHandlerController@filePreview']);
    Route::post('all', ['as'=>'all','uses'=>'UploadHandlerController@filePreviewMultiple']);
    Route::post('post-remove', ['as' => 'post.remove', 'uses' => 'UploadHandlerController@postRemove']);
    Route::post('remove-asset', ['as' => 'remove.asset', 'uses' => 'UploadHandlerController@removeAsset']);
    Route::post('editor', ['as' => 'editor', 'uses' => 'UploadHandlerController@editorUpload']);
    Route::get('manager', ['as' => 'manager', 'uses' => 'UploadHandlerController@editorManager']);
    Route::delete('manager-remove', ['as' => 'manager.remove', 'uses' => 'UploadHandlerController@editorManagerDelete']);
});

app/Models/Core/AccessModel.php
<?php
/**
 * Description: AccessModel.php PhpStorm.
 *
 * @package     amqit-mutilang
 * @author      alex
 * @created     03/12/2018, modified: 03/12/2018 19:19
 * @copyright   Copyright (c) 2018.
 */

namespace App\Models\Core;


use Illuminate\Database\Eloquent\Model;

class AccessModel extends Model
{
    protected $table = 'tb_access';
    protected $primaryKey = 'access_id';
    protected $guarded = ['created_at', 'updated_at'];
}

app/Models/Core/AuditModel.php
<?php
/**
 * Description: AuditModel.php PhpStorm.
 *
 * @package     amqit-mutilang
 * @author      alex
 * @created     03/12/2018, modified: 03/12/2018 19:19
 * @copyright   Copyright (c) 2018.
 */

namespace App\Models\Core;


use Illuminate\Database\Eloquent\Model;

class AuditModel extends Model
{
    protected $table = 'tb_logs';
    protected $primaryKey = 'log_id';
    protected $fillable = ['module', 'task', 'user_id', 'ipaddress', 'useragent', 'note'];
    protected $guarded = ['created_at', 'updated_at'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\Models\Core\UsersModel','user_id','user_id');
    }
}

app/Models/Core/ConfigModel.php
<?php
/**
 * Description: ConfigModel.php generated by PhpStorm.
 * @project     web-sekolah
 * @package     App\Models\Core
 * @author      alex
 * @created     2020-05-20, modified: 2020-05-20 22:33
 * @copyright   Copyright (c) 2020
 */

namespace App\Models\Core;


use Illuminate\Database\Eloquent\Model;

class ConfigModel extends Model
{
    protected $table = 'ms_config';
    protected $primaryKey = 'id';
    protected $fillable = [
        'params', 'updated_by'
    ];
    protected $guarded = ['created_at', 'updated_at'];
    protected $casts = [
        'params' => 'array'
    ];
}

app/Models/Services/UploadHandlerModel.php
<?php
/**
 * Description: UploadHandlerModel.php PhpStorm.
 *
 * @package     amqit-mutilang
 * @author      alex
 * @created     31/01/2018, modified: 31/01/2018 00:59
 * @copyright   Copyright (c) 2018.
 */

namespace App\Models\Services;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\File;
use Intervention\Image\Facades\Image;

/**
 * @property mixed category
 * @property mixed title
 * @property string base_folder
 * @property string base_path
 * @property null|string mime_type
 * @property mixed created_at
 * @property int|null created_by
 * @property mixed assetId
 */
class UploadHandlerModel extends Model
{
    protected $table = 'ms_assets';
    protected $primaryKey = 'assetId';
    protected $fillable = ['category','title','base_folder','base_path','mime_type','extension','size', 'created_by', 'updated_by'];
    protected $guarded = ['created_at','updated_at'];

    /**
     * @return mixed
     */
    public function getFileURLAttribute()
    {
        return config('general.files.upload') . $this->base_folder . '/' . $this->base_path;
    }

    /**
     * @return mixed
     */
    public function getFullURLAttribute()
    {
        $isExists = File::exists(public_path($this->getFileURLAttribute()));
        return $isExists ? asset($this->getFileURLAttribute()) : 'https://placeimg.com/800/600/tech';
    }

    /**
     * @param $width
     * @param $height
     * @return string
     */
    public function getImageThumbnailAttribute($width, $height)
    {
        $path = config('general.files.upload') . $this->base_folder . '/' . $this->base_path;
        $isExists = File::exists(public_path($path));
        if ($isExists) {
            $image = Image::make(public_path($path));
            $file = $image->filename . '_' . $width . 'x' . $height . '.' . $image->extension;
            $trimPath = explode($image->basename, $path);

            return asset($trimPath[0] . 'thumbs/' . $file);
        } else {
            return 'https://placeimg.com/' . $width . '/' . $height . '/tech';
        }
    }
}

app/Http/Controllers/Backend/Core/AccountController.php
<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 2019-03-25
 * Time: 02:51
 */

namespace App\Http\Controllers\Backend\Core;


use App\Exceptions\GeneralException;
use App\Http\Controllers\Controller;
use App\Repositories\Core\UserProfileRepository;
use App\Repositories\Core\UsersRepository;
use App\Repositories\Handler\UploadHandlerRepository;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use Intervention\Image\Facades\Image;

class AccountController extends Controller
{
    private $route = "admin.account";
    private $template = "backend.core.users";
    /**
     * @var UsersRepository
     */
    private $usersRepository;
    /**
     * @var UserProfileRepository
     */
    private $profileRepository;
    /**
     * @var UploadHandlerRepository
     */
    private $handlerRepository;

    /**
     * AccountController constructor.
     * @param UsersRepository $usersRepository
     * @param UserProfileRepository $profileRepository
     * @param UploadHandlerRepository $handlerRepository
     */
    public function __construct(UsersRepository $usersRepository,
                                UserProfileRepository $profileRepository,
                                UploadHandlerRepository $handlerRepository)
    {
        $this->usersRepository = $usersRepository;
        $this->profileRepository = $profileRepository;
        $this->handlerRepository = $handlerRepository;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        if (session('logged_in') == false){
            abort('403');
        }

        $keyId = session('uid');
        $user = $this->usersRepository->getById($keyId);
        $data['user'] = $user;
        $data['route'] = $this->route;
        $data['title'] = __('forms.user.account');
        return view($this->template.'.account', $data);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function password()
    {
        if (session('logged_in') == false){
            abort('403');
        }

        $keyId = session('uid');
        $user = $this->usersRepository->getById($keyId);
        $data['user'] = $user;
        $data['route'] = $this->route;
        $data['title'] = __('strings.common.user.change_password');
        return view($this->template.'.password', $data);
    }

    /**
     * Profile data update function
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws GeneralException
     */
    public function store(Request $request)
    {
        if ($request->all()) {
            $key = Auth::id();
            Validator::make($request->all(), [
                'fullname' => 'required',
                'email' => 'required|' . Rule::unique('tb_users')->ignore($key, 'user_id')
            ],[
                'fullname.required' => __('validation.required', ['field' => __('forms.user.fullname')]),
                'email.required' => __('validation.required', ['field' => __('forms.user.email')]),
                'email.unique' => __('validation.unique', ['field' => __('forms.user.email')])
            ])->validate();

            $data = $request->all();
            $profile = request()->except(['_token', 'group_id', 'fullname', 'email', 'wali_kelas', 'secure_id', 'regnumber', 'siswa_kelas', 'propic']);
            if ($request->hasFile('propic')) {
                $image = $request->file('propic');
                $folder = 'users';
                $destinationPath = public_path(uploadFolder() . $folder);
                $imageMime = $image->getClientMimeType();
                $imageExtension = $image->getClientOriginalExtension();
                $imageSize = $image->getSize();
                $newFilename = uniqid('user_').'.'.$imageExtension;

                if (!File::exists($destinationPath)) {
                    File::isDirectory($destinationPath) or File::makeDirectory($destinationPath, 0777, true, true);
                }

                $uploaded = $image->move($destinationPath,$newFilename);
                if ($uploaded) {
                    $image = Image::make($destinationPath.'/'.$newFilename);
                    $thumbDir = $image->dirname . '/thumbs';
                    if (!File::exists($thumbDir)) {
                        File::makeDirectory($thumbDir, 0777, true, true);
                    }

                    $thumbnail = $thumbDir . '/' . $image->filename . '_' . 350 . 'x' . 350 . '.' . $image->extension;
                    if (!File::exists($thumbnail)) {
                        $image->fit(350, 350)->save($thumbnail);
                    }

                    $insert = [
                        'category' => 'USER',
                        'title' => request('fullname'),
                        'base_folder' => $folder,
                        'base_path' => $newFilename,
                        'mime_type' => $imageMime,
                        'extension' => $imageExtension,
                        'size' => $imageSize,
                        'created_by' => Auth::id()
                    ];
                    $insert['created_by'] = Auth::id();
                    $asset = $this->handlerRepository->create($insert);
                    $data['avatar'] = $asset->assetId;
                }
            }

            $data['user_id'] = $key;
            $data['updated_by'] = $key;
            $data['updated_at'] = Carbon::now();
            $result = $this->usersRepository->updateById($key,$data);
            if ($result) {
                $user = $this->usersRepository->getById($key);
                $userProfile = $user->profile();

                $display = explode(' ', $request->input('fullname'));
                $profile['user_id'] = $user->user_id;
                $profile['display_name'] = $request->input('display_name') ? $request->input('display_name') : $display[0];

                if ($userProfile->count() > 0) {
                    $userProfile->update($profile);
                } else {
                    $this->profileRepository->create($profile);
                }

                if ($key == $user->user_id) {
                    $session = [
                        'fullname' => $user->fullname,
                        'email' => $user->email,
                        'display' => @$user->profile && @$user->profile->display_name ? $user->profile->display_name : $user->fullname,
                        'avatar' => @$user->photo ? $user->photo->file_url : null,
                        'thumbnail' => @$user->photo ? getThumbnail($user->photo->file_url, 350, 350) : null,
                    ];
                    session($session);
                }
                return redirect()->route($this->getRoute('index'))->with('message', __('strings.common.messages.update.success'))
                    ->with('type', 'success');
            } else {
                throw new GeneralException(__('strings.common.messages.update.failed'));
            }
        } else {
            throw new GeneralException(__('strings.common.messages.empty'));
        }
    }

    /**
     * Change password function
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws GeneralException
     */
    public function save(Request $request)
    {
        if ($request->all()) {
            $key = Auth::id();
            $user = $this->usersRepository->getById($key);
            $check = Hash::check($request->input('oldpassword'), $user->password);
            if(!$check){
                return redirect()->back()->with('message', __('strings.common.user.old_pass_wrong'))
                    ->with('type', 'error');
            }

            Validator::make($request->all(), [
                'oldpassword' => 'required',
                'upassword' => 'required|confirmed|min:6|max:15',
                'upassword_confirmation' => 'required|min:6|max:15',
            ],[
                'oldpassword.required' => __('validation.required', ['field' => __('strings.common.user.oldpassword')]),
                'upassword.required' => __('validation.required', ['field' => __('strings.common.user.newpassword')]),
                'upassword_confirmation.required' => __('validation.required', ['field' => __('strings.common.user.password_retype')]),
                'upassword.confirmed' => __('validation.confirmed', ['field' => __('strings.common.user.newpassword')]),
                'upassword.min' => __('validation.min.string', ['field' => __('strings.common.user.newpassword')]),
                'upassword.max' => __('validation.max.string', ['field' => __('strings.common.user.newpassword')]),
                'upassword_confirmation.min' => __('validation.min.string', ['field' => __('strings.common.user.password_retype')]),
                'upassword_confirmation.max' => __('validation.max.string', ['field' => __('strings.common.user.password_retype')]),
            ])->validate();

            $data = $request->all();
            $data['password'] = Hash::make($request->input('upassword'));
            $data['updated_by'] = $key;
            $data['updated_at'] = Carbon::now();
            $result = $this->usersRepository->updateById($key,$data);
            if ($result) {
                return redirect()->route($this->getRoute('index'))->with('message', __('passwords.reset'))
                    ->with('type', 'success');
            } else {
                throw new GeneralException(__('strings.common.messages.update.failed'));
            }
        } else {
            throw new GeneralException(__('strings.common.messages.empty'));
        }
    }

    /**
     * @param string $prefix
     * @return string
     */

resources/views/backend/core/users/form.blade.php
@extends('backend._container.layout')
@section('title', $title)
@section('breadcrumbs')
    {{ Breadcrumbs::render('users') }}
@stop
@section('content')
    <div class="container-fluid">
        <div id="ui-view">
            <div>
                <div class="fade-in">
                    <div class="card card-accent-secondary">
                        <div class="card-header d-flex align-items-center">
                            <h5 class="card-title mb-0"><i class="fas fa-edit"></i> {{$title}}</h5>
                            <button class="btn btn-secondary mfs-auto mfe-1 d-print-none"
                                    onclick="clickButton('{{route($route.'.index')}}')"><span
                                        class="fas fa-arrow-left"></span> @lang('buttons.general.back')</button>
                        </div>
                        {!! Form::open(['route' => $route.'.store','id' => 'appForm', 'novalidate' => 'novalidate']) !!}
                        <div class="card-body">
                            @include('backend.errors.list')
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group {{ $errors->has('username') ? ' has-error' : '' }}">
                                        {!! Form::label('username', __('strings.common.user.username'),['class' => 'control-label required-label']); !!}
                                        {!! Form::text('username', @$user->username ? @$user->username : old('username'),['autocomplete' => 'off', 'readonly' => @$user->username ? true : false, 'class' => 'validate[required,minSize[5],maxSize[10]] form-control', 'minlength' => 5, 'maxlength' => 10]); !!}
                                        <span class="help-block">
                                    <ul class="list-unstyled text-note em">
                                        <li>{!! __('placeholder.forms.rules',['attribute' => __('strings.common.user.username'),'min' => 5, 'max' => 10]) !!}</li>
                                    </ul>
                                </span>
                                    </div>
                                    <div class="form-group {{ $errors->has('group_id') ? ' has-error' : '' }}">
                                        {!! Form::label('group_id', __('module.group.module'),['class' => 'control-label required-label']); !!}
                                        {!! Form::select('group_id', [], @$user->group_id ? @$user->group_id : old('group_id'), ['id' => 'group_id', 'required' => true, 'class' => 'form-control select2']); !!}
                                    </div>
                                    <div class="form-group {{ $errors->has('fullname') ? ' has-error' : '' }}">
                                        {!! Form::label('fullname', __('forms.user.fullname'),['class' => 'control-label required-label']); !!}
                                        {!! Form::text('fullname', @$user->fullname ? @$user->fullname : old('fullname'), ['required' => true, 'class' => 'form-control']); !!}
                                    </div>
                                    <div class="form-group {{ $errors->has('email') ? ' has-error' : '' }}">
                                        {!! Form::label('email', __('forms.user.email'),['class' => 'control-label required-label']); !!}
                                        {!! Form::email('email', @$user->email ? @$user->email : old('email'), ['required' => true, 'class' => 'form-control']); !!}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group {{ $errors->has('upassword') ? ' has-error' : '' }}">
                                        {!! Form::label('password', __('strings.common.user.password'),['class' => 'control-label required-label']); !!}
                                        <div class="input-group">
                                            {!! Form::password('upassword', ['id' => 'password', 'autocomplete' => 'new-password', 'class' => 'validate[required,minSize[6],maxSize[15]] form-control no-icon', 'maxlength' => 15, 'placeholder' => __('placeholder.passwords.leave_blank')]); !!}
                                            <div class="custom-append" onclick="togglePassword('password')">
                                                <i id="icon-append_password" class="fas fa-eye-slash"></i>
                                            </div>
                                        </div>
                                        <span class="help-block">
                                    <ul class="list-unstyled text-note em">
                                        <li>{!! __('placeholder.forms.rules',['attribute' => __('strings.common.user.password'),'min' => 6, 'max' => 15]) !!}</li>
                                    </ul>
                                </span>
                                    </div>
                                    <div class="form-group {{ $errors->has('upassword_confirmation') ? ' has-error' : '' }}">
                                        {!! Form::label('password_confirmation', __('strings.common.user.password_retype'),['class' => 'control-label required-label']); !!}
                                        <div class="input-group">
                                            {!! Form::password('upassword_confirmation', ['id' => 'password_confirmation', 'class' => 'form-control no-icon', 'placeholder' => __('placeholder.passwords.confirm_pass')]); !!}
                                            <div class="custom-append"
                                                 onclick="togglePassword('password_confirmation')">
                                                <i id="icon-append_password_confirmation" class="fas fa-eye-slash"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group {{ $errors->has('active') ? ' has-error' : '' }}">
                                        {!! Form::label('active', __('strings.common.status.label'),['class' => 'control-label required']); !!}
                                        <div>
                                            <label class="check" style="margin-right: 15px">
                                                <input type="radio" class="icheckbox" name="active" id="is_active"
                                                       value="1" {!! @$user->active == 1 ? 'checked' : '' !!}/> @lang('strings.common.status.active')
                                                <span></span>
                                            </label>

                                            <label class="check" style="margin-right: 15px">
                                                <input type="radio" class="icheckbox" name="active" id="is_inactive"
                                                       value="0" {!! @$user->active == 0 ? 'checked' : '' !!}/> @lang('strings.common.status.inactive')
                                                <span></span>
                                            </label>

                                            <label class="check">
                                                <input type="radio" class="icheckbox" name="active" id="is_blocked"
                                                       value="2" {!! @$user->active == 2 ? 'checked' : '' !!}/> @lang('strings.common.status.blocked')
                                                <span></span>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer text-right">
                            {!! Form::hidden('secure_id', @$secure_id) !!}
                            <button onclick="clickButton('{{route($route.'.index')}}')" class="ladda-button"
                                    type="button" data-size="s" data-color="red" data-style="slide-right"><i
                                        class="fas fa-times"></i> <span
                                        class="ladda-label">@lang('buttons.general.cancel')</span></button>
                            <button type="submit" class="ladda-button" data-size="s" data-color="green"
                                    data-style="slide-right"><i
                                        class="fas fa-save"></i> <span
                                        class="ladda-label">@lang('buttons.general.save')</span></button>
                        </div>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@push('after-scripts')
    <script type="text/javascript">
        function togglePassword(input) {
            let elm = $('#' + input);
            let icon = $('#icon-append_' + input);

            icon.toggleClass('fa-eye fa-eye-slash');
            if (elm.attr('type') === 'password') {
                elm.attr('type', 'text');
            } else {
                elm.attr('type', 'password');
            }
        }
        $('document').ready(function () {
            let $groupId = $('#group_id');

            $('#password').prop('required', true);
            $('#password_confirmation').prop('required', true);

            @if(@$secure_id)
            $('#password').prop('required', false);
                $('#password_confirmation').prop('required', false);
            @endif

            $groupId.cascadeCombo("{{route('common.group')}}", "{!! @$user->group_id ? @$user->group_id : old('group_id') !!}", null, "{!! __('forms.choose.user_group') !!}");
        });
    </script>
@endpush